### ISSUE TITLE
An error occured trying to load a proxy into diminvo.Diminvo.PROXY

### ISSUE THREAD

**Issue by portwatcher** [dawnflyc/Diminvo#1]
I'm running a minecraft hosting service, my user(which is server owner) reported to me that he couldn't start server as he got error as follows:

![S488`_K)H)~}FNXLZ@0KNPK](https://user-images.githubusercontent.com/2919533/120328495-70de0b00-c31d-11eb-8f4d-e3370d115269.png)

server software: SpongeForge 1.12.2
Forge Version: 2838
Diminvo Version: diminvo-1.2.jar

BTW, Nice Mod, great work!

**Comment by dawnflyc** [comment]
who are you?

Jury Schon ***@***.***> 于2021年6月1日周二 下午9:13写道：

**Comment by dawnflyc** [comment]
This is a mistake, I have fixed it. But my couseforge account is lost, I will post the new version on github.
